import pandas as pd
import duckdb


def read_preME_excel_data(file_path, peak):
    try:
        # Read the specified range from the Excel file
        df = pd.read_excel(
            file_path, 
            sheet_name=f'cordon_{peak}', 
            usecols='A:E',  # Columns A through E
        )

        df['peak'] = peak


        return df[['origin', 'destination', 'peak', 'time', 'vehicle', 'trips']]

    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return None
    
def read_postME_excel_data(file_path, peak):
    try:
        # Read the specified range from the Excel file
        df = pd.read_excel(
            file_path, 
            sheet_name=f'PostME_{peak}', 
            usecols='A:E',  # Columns A through E
        )

        df['peak'] = peak

        return df[['origin', 'destination', 'peak', 'time', 'vehicle', 'trips']]

    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return None
    

def get_od_from_path(select_link_groups, path_file, turn_lookup_df):
    """
    Get origin-destination pairs from path data based on select link groups.
    
    Args:
        select_link_groups (list): List of lists containing link IDs for each group.
        path_file (str): Path to the file containing path data.
        turn_lookup (dict): Dictionary mapping turns to their corresponding links.
    
    Returns:
        pd.DataFrame: DataFrame containing origin, destination, and percentage of vehicles on path.
    """
    conn = duckdb.connect()
    
    # Load path data
    conn.sql(f"CREATE TABLE path AS SELECT * FROM read_csv_auto('{path_file}')")
    
    new_select_link_groups = []
    # for each group of select links and each object in the group, check if the object is in the turn lookup file turn column
    for group in select_link_groups:
        new_group = []
        for obj in group:
            if int(obj) in turn_lookup_df['turn'].values:
                # if it is, get the row from the turn lookup file
                turn_row = turn_lookup_df[turn_lookup_df['turn'] == int(obj)]
                # get the origin link_id from the row
                origin_link_id = turn_row['origin'].values[0]
                destination_link_id = turn_row['destination'].values[0]
                # print(f"Object {obj} is in the turn lookup file with origin_link_id {origin_link_id} and destination_link_id {destination_link_id}.")
                # remove the object from the select_link_groups
                new_group.extend([str(origin_link_id), str(destination_link_id)])
            else:
                # print(f"Object {obj} is not in the turn lookup file.")
                new_group.extend([obj])
        new_select_link_groups.append(new_group)


    # Create conditions for the SQL query
    def create_link_conditions(link_groups):
        or_conditions = []
        for group in link_groups:
            if len(group) == 1:
                condition = f"list_contains(links, '{group[0]}')"
            else:
                and_conditions = [f"list_contains(links, '{link}')" for link in group]
                condition = "(" + " AND ".join(and_conditions) + ")"
            or_conditions.append(condition)
        return " OR ".join(or_conditions)
    # print(f"New select link groups: {new_select_link_groups}")
    query = f"""
    SELECT 
      origin,
      destination,
      string_split(path, '-') as links,
      "veh generated" AS veh_generated
    FROM path
    WHERE {create_link_conditions(new_select_link_groups)}
    """

    sl_volume = conn.sql(query).df()[['origin', 'destination', 'veh_generated']]

    # aggregate the veh_generated by origin and destination
    sl_volume_agg = sl_volume.groupby(['origin', 'destination']).sum().reset_index()

    # calculate the percentage of veh_generated for each origin-destination pair
    sl_volume_agg['percentage'] = sl_volume_agg['veh_generated'] / sl_volume_agg['veh_generated'].sum()

    return sl_volume_agg[['origin', 'destination', 'percentage']]


def modify_vehicle_percentages(df, percentages):
    """
    Modify the vehicle percentages in the DataFrame based on the provided percentages.
    """
    # Add a column to differentiate between Cars and Trucks
    df['vehicle_type'] = df['vehicle'].apply(lambda x: 'Car' if 'Car' in x else 'Truck')

    # Group by origin, destination, and vehicle_type, and sum the trips
    df_grouped = df.groupby(['origin', 'destination', 'vehicle_type', 'profile_id'])['trips'].sum().reset_index()

    # Create a list to hold the new rows
    new_rows = []

    # Loop over each row and apply percentages for that vehicle type
    for _, row in df_grouped.iterrows():
        for vehicle, pct in percentages.items():
            vtype = 'Car' if 'Car' in vehicle else 'Truck'
            if row['vehicle_type'] == vtype:
                new_rows.append({
                    'origin': row['origin'],
                    'destination': row['destination'],
                    'vehicle': vehicle,
                    'profile_id': row['profile_id'],
                    'trips': row['trips'] * (pct / 100)
                })

    # Create the final DataFrame
    result_df = pd.DataFrame(new_rows)

    return result_df



def process_demand(file_path, output_path, postME, peaks, path_files, turn_lookup_file, version, uc_splits):
    """
    Process the demand data from the Excel file.
    
    Args:
        file_path (str): Path to the Excel file containing demand data.
        postME (bool): Flag indicating if the data is post-ME.
        peaks (list): List of peak periods to process.
        uc_splits (dict): Dictionary containing user class splits for each peak period.
    """
    
    # If postME is True, we will not read the preME data
    if postME:
        demand = pd.DataFrame()
        for peak in peaks:
            
            print(f"Reading data for {peak} peak...")
            data = read_postME_excel_data(file_path, peak)
            if data is not None:
                # Append the data to the main DataFrame
                if 'demand' in locals():
                    demand = pd.concat([demand, data], ignore_index=True)
                else:
                    demand = data
                print(f"Data for {peak} peak read successfully.")
            else:
                print(f"Failed to read data for {peak} peak.")

        # aggregate the demand by origin, destination, peak and vehicle, summing trips
        demand = demand.groupby(['origin', 'destination', 'peak', 'vehicle']).agg({'trips': 'sum'}).reset_index()

        # sum demand by peak and vehicle
        demand_vehicle_totals = demand.groupby(['peak', 'vehicle']).agg({'trips': 'sum'}).reset_index()
        demand_peak_total = demand_vehicle_totals.groupby('peak').agg({'trips': 'sum'}).reset_index()

        # calculate the percentage of each vehicle type in each peak
        demand_vehicle_totals = demand_vehicle_totals.merge(demand_peak_total, on='peak', suffixes=('', '_total'))
        demand_vehicle_totals['percentage'] = demand_vehicle_totals['trips'] / demand_vehicle_totals['trips_total']


        adjustments = pd.DataFrame()
        for peak in peaks:
            print(f"Processing adjustments for {peak} peak...")
            # read in the adjustment values
            adjustments_temp = pd.read_excel(
                file_path,
                sheet_name=f'adjustments_{peak}'
            )
            adjustments_temp['peak'] = peak
            adjustments = pd.concat([adjustments, adjustments_temp], ignore_index=True)

        # sum the adjustments by peak and print
        am_total = adjustments[adjustments['peak'] == 'am'].agg({'adjustment': 'sum'}).values[0]
        pm_total = adjustments[adjustments['peak'] == 'pm'].agg({'adjustment': 'sum'}).values[0]
        print(f"Total adjustments - AM: {am_total}, PM: {pm_total}")

        turn_lookup_df = pd.read_csv(turn_lookup_file)
        sl_adjustments_df = pd.DataFrame()
        # calculate the select link adjustments
        for peak in peaks:
            peak_sl_adjustments = pd.DataFrame()
            print(f"Calculating select link adjustments for {peak} peak...")
            # read in the select link adjustments
            select_link_adjustments = pd.read_excel(
                file_path,
                sheet_name=f'sl_adjustments_{peak}'
            )
            if select_link_adjustments.empty:
                print(f"No select link adjustments found for {peak} peak. Skipping...")
                continue
            else:
                print(f"Select link adjustments found for {peak} peak. Processing...")
                # loop through section/turn in the dataframe
                for index, row in select_link_adjustments.iterrows():
                    object = row['section/turn']
                    # check if the object has a comma
                    if ',' in str(object):
                        # if it does, split it into a list
                        object = [int(x.strip()) for x in str(object).split(',')]
                        select_link_groups = [[str(x) for x in object]]
                    else:
                        object = int(object)
                        select_link_groups = [[str(object)]]
                    adjustment = row['adjustment']
                    sl_volume_temp = get_od_from_path(
                        select_link_groups,
                        path_files[peak],
                        turn_lookup_df
                    )
                    # multiply the percentage by the adjustment value
                    sl_volume_temp['adjustment'] = sl_volume_temp['percentage'] * adjustment
                    sl_volume_temp = sl_volume_temp[['origin', 'destination', 'adjustment']]
                    peak_sl_adjustments = pd.concat([peak_sl_adjustments, sl_volume_temp], ignore_index=True)
                # aggregate the adjustments by origin and destination
                peak_sl_adjustments = peak_sl_adjustments.groupby(['origin', 'destination']).sum().reset_index()
                peak_sl_adjustments['peak'] = peak
                sl_adjustments_df = pd.concat([sl_adjustments_df, peak_sl_adjustments], ignore_index=True)

        # concat sl_adjustments_df with the adjustments
        adjustments = pd.concat([adjustments, sl_adjustments_df], ignore_index=True)
        # aggregate the adjustments by origin, destination and peak
        adjustments = adjustments.groupby(['origin', 'destination', 'peak']).sum().reset_index()
        # merge the adjustments with the demand data
        demand = demand.merge(adjustments, on=['origin', 'destination', 'peak'], how='left')

        # merge in the demand_vehicle_totals
        demand = demand.merge(demand_vehicle_totals, on=['peak', 'vehicle'], how='left', suffixes=('', '_vehicle_total'))
        # multiply the adjustments by the percentage of each vehicle type in each peak
        demand['trips'] = demand['trips'] + demand['adjustment'] * demand['percentage']
        # keep only the relevant columns
        demand = demand[['origin', 'destination', 'peak', 'vehicle', 'trips']]
        # calculate the total trips by peak
        total_trips_by_peak = demand.groupby('peak').agg({'trips': 'sum'}).reset_index()
        print("Total trips by peak after adjustments:")
        print(total_trips_by_peak)
    else:
        
        # Initialize an empty DataFrame to hold all demand data
        demand = pd.DataFrame()
        for peak in peaks:
            
            print(f"Reading data for {peak} peak...")
            data = read_preME_excel_data(file_path, peak)
            if data is not None:
                # Append the data to the main DataFrame
                if 'demand' in locals():
                    demand = pd.concat([demand, data], ignore_index=True)
                else:
                    demand = data
                print(f"Data for {peak} peak read successfully.")
            else:
                print(f"Failed to read data for {peak} peak.")

        # read in the expansion factors
        exp_factors = pd.read_excel(
            file_path,
            sheet_name='expansion_factors',
            usecols='A:B',  # Columns A and B
            # nrows=4,  # Read the first 4 rows
            header=0  # Use the first row as header
        )

        # merge the expansion factors with the demand data
        demand = demand.merge(exp_factors, left_on='peak', right_on='peak', how='left')
        # multiply the trips by the expansion factor
        demand['trips'] = demand['trips'] * demand['factor']
        demand = demand.drop(columns=['factor'])

    # apply demand profiles
    # read in the profile sector system
    profile_sectors = pd.read_excel(
        file_path,
        sheet_name="groups"
    )

    # join the profile sectors to the demand for the origin
    demand = demand.merge(profile_sectors, left_on='origin', right_on='ID', how='left')
    # join the profile sectors to the demand for the destination
    demand = demand.merge(profile_sectors, left_on='destination', right_on='ID', how='left', suffixes=('_origin', '_destination'))
    # drop the name, time and ID columns
    demand = demand.drop(columns=['Name_origin', 'Name_destination', 'ID_origin', 'ID_destination'])
    # drop time column if it exists
    if 'time' in demand.columns:
        demand = demand.drop(columns=['time'])

    # read in the profile lookup table
    profile_lookup = pd.DataFrame()
    for peak in peaks:
        profile_lookup_temp = pd.read_excel(
            file_path,
            sheet_name=f'profile_lookup_{peak}'
        )



        # convert from a square matrix to a long format
        profile_lookup_temp = profile_lookup_temp.melt(id_vars=['profile'], var_name='group_destination', value_name='profile_id')
        # rename 'profile' to 'group_origin'
        profile_lookup_temp = profile_lookup_temp.rename(columns={'profile': 'group_origin'})

        profile_lookup_temp['peak'] = peak

        profile_lookup = pd.concat([profile_lookup, profile_lookup_temp], ignore_index=True)

    # merge the profile lookup with the demand
    demand = demand.merge(profile_lookup, left_on=['group_origin', 'group_destination', 'peak'], right_on=['group_origin', 'group_destination', 'peak'], how='left')
    # drop the group_origin and group_destination columns
    demand = demand.drop(columns=['group_origin', 'group_destination'])

    # read in the demand profiles
    for peak in peaks:
        demand_profile = pd.read_excel(
            file_path,
            sheet_name=f'demand_profiles_{peak}'
        )

        demand_peak = demand[demand['peak'] == peak].copy()

        print(uc_splits[peak])

        # adjust the user class percentage splits
        demand_peak = modify_vehicle_percentages(demand_peak, uc_splits[peak])

        # drop the peak column
        # demand_peak = demand_peak.drop(columns=['peak'])
        # merge the demand profile with the demand
        demand_peak = demand_peak.merge(demand_profile, left_on='profile_id', right_on='profile_id', how='left')
        
        # get the columns that are not origin, destination, vehicle, trips and profile_id
        demand_columns = demand_peak.columns.difference(['origin', 'destination', 'vehicle', 'trips', 'profile_id'])
        demand_columns = demand_columns.tolist()
        for column in demand_columns:
            demand_peak[column] = demand_peak[column] * demand_peak['trips']

        # drop the trips and profile_id columns
        demand_peak = demand_peak.drop(columns=['trips', 'profile_id'])
        # save the demand to a csv file
        if postME:
            prefix = 'postME_'
        else:
            prefix = 'preME_'
    
        demand_peak.to_csv(f'{output_path}{prefix}{peak}_profiled_base_demand_{version}.csv', index=False)
        print(f"{peak} Profiled Demand data exported to {output_path}{prefix}{peak}_profiled_base_demand_{version}.csv")