import duckdb
import pandas as pd

def get_od_from_path(select_link_groups, path_file, turn_lookup_df):
    """
    Get origin-destination pairs from path data based on select link groups.
    
    Args:
        select_link_groups (list): List of lists containing link IDs for each group.
        path_file (str): Path to the file containing path data.
        turn_lookup (dict): Dictionary mapping turns to their corresponding links.
    
    Returns:
        pd.DataFrame: DataFrame containing origin, destination, and percentage of vehicles on path.
    """
    conn = duckdb.connect()
    
    # Load path data
    conn.execute(f"CREATE TABLE path AS SELECT * FROM read_csv_auto('{path_file}')")

    # group by origin, destination and path and sum veh generated
    conn.execute("""
    CREATE OR REPLACE TABLE path AS
    SELECT
      origin,
      destination,
      path,
      SUM("veh generated") AS veh_generated
    FROM path
    GROUP BY origin, destination, path
    """)

    new_select_link_groups = []
    # for each group of select links and each object in the group, check if the object is in the turn lookup file turn column
    for group in select_link_groups:
        new_group = []
        for obj in group:
            if int(obj) in turn_lookup_df['turn'].values:
                # if it is, get the row from the turn lookup file
                turn_row = turn_lookup_df[turn_lookup_df['turn'] == int(obj)]
                # get the origin link_id from the row
                origin_link_id = turn_row['origin'].values[0]
                destination_link_id = turn_row['destination'].values[0]
                print(f"Object {obj} is in the turn lookup file with origin_link_id {origin_link_id} and destination_link_id {destination_link_id}.")
                # remove the object from the select_link_groups
                new_group.extend([str(origin_link_id), str(destination_link_id)])
            else:
                print(f"Object {obj} is not in the turn lookup file.")
                new_group.extend([obj])
        new_select_link_groups.append(new_group)


    # Create conditions for the SQL query
    def create_link_conditions(link_groups):
        or_conditions = []
        for group in link_groups:
            if len(group) == 1:
                condition = f"list_contains(links, '{group[0]}')"
            else:
                and_conditions = [f"list_contains(links, '{link}')" for link in group]
                condition = "(" + " AND ".join(and_conditions) + ")"
            or_conditions.append(condition)
        return " OR ".join(or_conditions)
    
    query = f"""
    SELECT 
      origin,
      destination,
      string_split(path, '-') as links,
      veh_generated
    FROM path
    WHERE {create_link_conditions(new_select_link_groups)}
    """

    print(query)

    sl_volume = conn.sql(query).df()[['origin', 'destination', 'veh_generated']]

    # aggregate the veh_generated by origin and destination
    sl_volume_agg = sl_volume.groupby(['origin', 'destination']).sum().reset_index()

    # calculate the percentage of veh_generated for each origin-destination pair
    sl_volume_agg['percentage'] = sl_volume_agg['veh_generated'] / sl_volume_agg['veh_generated'].sum()

    return sl_volume_agg[['origin', 'destination', 'percentage']]